# Generated by Django 3.1.3 on 2024-02-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(max_length=1000)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(max_length=50)),
                ('last_name', models.TextField(max_length=50)),
            ],
            options={
                'db_table': 'service_request2',
            },
        ),
    ]
