# Generated by Django 3.1.3 on 2024-02-04 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20240204_1543'),
    ]

   # operations = [
    #    migrations.AlterModelTable(
     #       name='servicerequest',
      #      table='service_request2',
  #      ),
   # ]
