# Generated by Django 3.1.3 on 2024-02-04 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20240204_1548'),
    ]

    
