# Generated by Django 3.1.3 on 2024-02-04 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_auto_20240204_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='mobile_no',
            field=models.TextField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
